apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: gitlab-minio-registry-exception
  namespace: dev-minio
spec:
  exceptions:
  - policyName: restrict-image-registries
    ruleNames:
    - validate-registries
    - autogen-validate-registries
  match:
    any:
    - resources:
        kinds:
        - Deployment
        namespaces:
        - dev-minio
        names:
        - minio
    - resources:
        kinds:
        - Job
        namespaces:
        - dev-minio
        names:
        - minio-post-job
