name: Publish UDS Dependency Packages

on:
  push:
    branches:
      - main

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    name: Publish Packages

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Environment setup
        uses: ./.github/actions/setup
    
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Publish Packages
        run: uds run publish-packages
